// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)

import TimeupController from "./timeup_controller"
application.register("timeup", TimeupController)