
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  port: 5432
  host: localhost


development:
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: sigeobras_development

test:
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: sigeobras_test
production:
  <<: *default
  database: sigeobras_production
  username: sigeobras
  password: <%= ENV["SIGEOBRAS_DATABASE_PASSWORD"] %>
