
default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> %>
  username: <%= ENV.fetch('DB_NAME') { Rails.application.credentials.dig(:development, :username)} %>
  password: <%= ENV.fetch('DB_PASSWORD') { Rails.application.credentials.dig(:development, :password)} %>
  host:     <%= ENV.fetch('DB_HOST') { Rails.application.credentials.dig(:development, :host)} %>
  port: 5432


development:
  <<: *default
  database: sigeobras_development

test:
  <<: *default
  host: localhost
  database: sigeobras_test

production:
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch('DB_HOST') { Rails.application.credentials.dig(:production, :database)} %>
  username: <%= ENV.fetch('DB_NAME') { Rails.application.credentials.dig(:production, :username)} %>
  password: <%= ENV.fetch('DB_PASSWORD') { Rails.application.credentials.dig(:production, :password)} %>
  host:     <%= ENV.fetch('DB_HOST') { Rails.application.credentials.dig(:production, :host)} %>
 